example for feature #89
AngleSharp/AngleSharp.Css pull request #93
Opened 2021-11-07 16:57 UTC by jogibear9988

# Types of Changes

## Prerequisites

Please make sure you can check the following two boxes:

- [x] I have read the **CONTRIBUTING** document
- [x] My code follows the code style of this project

## Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [x] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

## Description

example for feature of minification of css #89

2021-11-25 16:17 UTC, FlorianRappl requested changes

2021-11-25 16:17 UTC, FlorianRappl commented on src/AngleSharp.Css/Constants/PropertyNames.cs
> +        public const String AlignContent = "align-content";
These are `public`. Can you keep them `static readonly`?

2021-11-26 16:01 UTC, jogibear9988 commented
I changed them to "const" so I could use them in a switch. But this could be reverted. Maybe it also works with new patern matching switch without that change.

What do you think about the overall concept? Is this a way to do Simplification/Minification of CSS as part of AngleSharp.Css ?

2021-11-26 16:17 UTC, FlorianRappl commented
> What do you think about the overall concept? Is this a way to do Simplification/Minification of CSS as part of AngleSharp.Css ?

Yeah we can leave it like that - personally I think for consistency having a dedicated formatter would make sense, too, but this also works.

> I changed them to "const" so I could use them in a switch. But this could be reverted. Maybe it also works with new patern matching switch without that change.

Understood - yes, I think it does work in the pattern matching style using references.

2023-06-14 21:53 UTC, FlorianRappl commented
Will be part of 1.0.0

2023-06-14 21:53 UTC, closed without merging